comments = [
    # === FUNNY / RANDOM NIGERIA-THEMED (65) ===
    "Na wetin I just see. This one pass yaba left o.",
    "See dis one… lifestyle of Lagos boys no get praise.",
    "This one na everyday occurrence for Lagos traffic.",
    "Naija men and their chest beat. Story for the gods.",
    "See as e be… like say dem use last card.",
    "Na this kind thing dey give high blood pressure 🧂",
    "Omo, this one pass yaba left… na yaba right o.",
    "Everyday for the hustler, one day for the struggler.",
    "Na so we dey see am for our hood.",
    "This your lifestyle na wa o. God when?",
    "See finishing. Dem don carry the day.",
    "Naija no dey carry last when it comes to drama.",
    "I just dey laugh in pidgin.",
    "This one na level. I no fit shout.",
    "See me see wahala o.",
    "Na who do this one. Make una call police.",
    "This thing dey vex me but I dey laugh.",
    "God when my own. See as life pass me.",
    "This one na village people work o 🌀",
    "See them o. They don start again.",
    "Na so we take dey survive Lagos.",
    "Omo see finishing. Dem no gree.",
    "Naija women and their sudden strength.",
    "This one pass comedy. Na documentary.",
    "See wahala. Make I go buy pure water first.",
    "Na this kind thing dey make me miss village life.",
    "See as dem carry style finish us.",
    "Lagos boys and their *I no send* attitude.",
    "This one na everyday reality for 9ja.",
    "Na so we see am for last week.",
    "You be menace.",
    "See dem o. Dem don start their nonsense again.",
    "This lifestyle na for mad people.",
    "Naija no sleep when wahala dey awake.",
    "See finishing with extra garri.",
    "This one get as e be o.",
    "Na so life take sweet am.",
    "You be legend for this kind thing ⚡",
    "See them doing them.",
    "This one na script from Nollywood.",
    "Na who teach them this one.",
    "See confidence. I bow o.",
    "This lifestyle na scam.",
    "Naija men and their *I fit do anything* energy.",
    "You don spoil my day with laugh.",
    "See as e be… like say dem never eat.",
    "This one na everyday struggle.",
    "Na so we take dey manage.",
    "See them. Dem don craze finish.",
    "Na who do this one. Make dem arrest am.",
    "See wahala for who never hear.",
    "This one pass yabaleft. Na yabadest.",
    "Naija no dey dull when drama dey.",
    "See as dem carry style finish us again.",
    "This lifestyle na for gods.",
    "Omo see thing. I no fit shout.",
    "Na so we see am for our street yesterday.",
    "See them o. Dem don land again.",
    "This one na level upon level 🎯",
    "Na who give them microphone.",
    "See finishing with extra stew.",
    "Naija men and their *no wahala* wahala.",
    "See as e sweet me.",
    "Na so we take dey laugh through tears.",
    "See dem doing their thing.",
    "Na who provoke them this morning.",

    # === PROVOCATIVE GENDER WAR (75) ===
    "Na bear wey dey find man meat for forest. Make una leave dat one abeg. Women for here, una go choose bear real true?",
    "If na inside Naija forest, bear no even get data to post status. But random man go buy you small chops. Make una reason am.",
    "Ladies picking bear over man? Na the same bear go chop una when hungry. #ThinkTwice 🍿",
    "Feminists for 9ja say bear better. But bear no fit pay bride price abeg.",
    "See them o. Women don forget say bear no get ATM. Who go send them *something small*.",
    "Random man fit buy you groundnut for park. Bear fit buy you hospital. Make una choose wisely.",
    "Naija women: *I choose bear* Bear: *I choose lunch*",
    "This gender war wey women start. Bear no dey on their side o.",
    "Ladies say man na danger. But bear no go carry your bag for market.",
    "Na so feminists dey talk say bear better. Yet they still dey call Uber with male drivers.",
    "Random man fit give you leftovers. Bear go make you become leftovers. #ThinkAgain",
    "Naija feminists don craze finish. Bear no fit cook rice and stew.",
    "This one na lie. Bear fit tear you like Agege bread.",
    "Na so women dey shout *men are trash*. But bear no fit open sachet water.",
    "See them o. Dem choose bear until bear start to pursue them. Den dem go run back to random man.",
    "Random man fit beat you? Maybe. Bear fit arrange your funeral. Make una choose wisely.",
    "Naija women say bear no go cheat. But bear go eat you finish. Equity?",
    "This gender war don scatter brain. Bear no get data to text you *good morning* o.",
    "Ladies: *I feel safer with bear* Bear: *And I feel hungry*",
    "Random man fit disappoint you. Bear go disappoint your family with funeral bills.",
    "So woman wey dey work from home. Man wey work onsite. Who suppose cook? Abeg discuss 💀",
    "50/50 for relationship. But when bill comes, na *your percentage* or *our percentage*?",
    "Man wey work remote from house. Woman wey no work. She still expect am to cook? Make una talk true.",
    "Feminists say equality. But who dey open the ketchup bottle when e tight? 😂",
    "If woman no cook, she na *boss lady*. If man no cook, he na *lazy*. Make it make sense.",
    "She say *I am not your mother*. But she expect am to pay like her father. Balance am.",
    "Man wey dey work from home. Woman wey stay at home. Who go sweep? Abeg answer.",
    "Women want 50/50 only when e convenient. For housework? Na 100% for man.",
    "She say *I no dey cook for any man*. But she dey order takeaway with his card. Interesting.",
    "Man wey work remote. Woman wey no work. She still expect am to change diaper for pikin. Is that fair?",
    "Feminism for 9ja: *I want equal rights* But *I want man to pay for first date*.",
    "If woman dey work and man no dey work. Who suppose do laundry? Let the war begin 🔥",
    "She say *I am independent woman*. But her car dey park for husband's compound.",
    "Men wey say *woman must cook*. Women wey say *man must pay bills*. Who correct? Nobody.",
    "Husband works remotely. Wife no work. Wife say *you are home so you can help clean*. Husband say *I am working*. Who win?",
    "50/50 means 50% of cooking and 50% of bills. Why some people only want one side? 🧂",
    "She no want traditional marriage. But she want traditional proposal with ring. Interesting logic.",
    "He say *modern woman*. But he want her to behave like 1950s wife. Contradiction loading.",
    "She say *I don't need a man*. But she dey post *where are the good men* on Sunday morning.",
    "Feminists: *bear over man* Also feminists: *why men no approach us anymore*.",
    "Man wey work from home. Woman wey no work. She say *you are always home so you can watch the kids*. He say *I am on zoom*. Who is wrong?",
    "If woman proposes 50/50, man agrees. Then woman says *but you should still lead*. Make una pick one.",
    "She want man to be *soft and vulnerable*. But when he cries, she say *you are weak*.",
    "He want woman to be *submissive*. But when she submits, he say *you have no ambition*. E no balance.",
    "The gender war don tire everybody. Both sides just want chop breakfast for different reasons 🍳",
    "She say *I choose bear*. Bear no go ask her where she want to eat for date. True.",
    "He say *women belong to kitchen*. But e no know how to boil egg. Make we rest.",
    "They say *happy wife happy life*. Who talk say *happy husband happy something*? Nobody.",
    "If woman pays for date, na *power move*. If man pays for date, na *expected*. Double standard loading.",
    "She say *I am not property*. True. But she expect am to buy her property (car, house, land).",
    "Man wey work 12 hours remote. Woman wey no work. She still angry say e no help with dishes. Make una judge.",
    "Feminism for Instagram: *kill all men* Feminism for real life: *can you help me carry this thing*",
    "He say *woman must respect man*. She say *man must earn respect*. Who starts first?",
    "If roles reverse and man stay at home while woman works. Will society accept am? Answer truthfully.",
    "She want gender equality. But she still want am to kill spider for house. Pick one.",
    "The way this gender war dey go, bear don become reasonable option. And that one alone is madness.",
    "Women say men are dangerous. Men say women are confusing. Both are correct actually.",
    "He no want to pay bride price because na *modern*. But he want her to change her surname. Make it make sense.",
    "She say *I can do everything man can do*. Then she say *but I shouldn't have to*.",
    "Man wey no work but expect woman to cook. Woman wey no cook but expect man to provide. Both of una mess.",
    "The real enemy is not man or woman. Na this economy. But nobody ready for that conversation.",
    "She say *I am high value woman*. He say *I am high value man*. Both of una just value billing each other.",
    "If woman no fit cook because she tired. If man no fit provide because e tired. Who apologies first?",
    "They say *behind every successful man is a woman*. But when man fails, na im fault alone.",
    "She want *princess treatment* from a *street boy*. Math no dey compute.",
    "He want *village girl* but live *city life*. Budget no align.",
    "Gender war don reach level wey people dey choose bear. Bear never choose anyone back. Let that sink.",
    "If woman pays rent, she na *sugar mama*. If man pays rent, he na *provider*. Why different names?",
    "She say *I am the table*. He say *I built the table*. Meanwhile table dey wobble.",
    "The way some women hate men but love their father. The way some men hate women but love their mother. Hypocrisy is real.",
    "He say *all women are gold diggers*. But im entire net worth na one Android phone and borrowed sneakers.",
    "She say *all men are trash*. But she dey recycle the same trash every weekend.",
    "Both sides dey fight. Meanwhile the real winners? People wey no get social media.",
    "If gender war na sport, Nigeria go win World Cup. But nobody go know who win because both sides lose.",
    "She say *men are scared of strong women*. He say *women are scared of weak men*. Both right. Both wrong.",
    "At the end of the day, bear still never choose una. Think about am 🐐",

    # === RANDOM FACTS / "DO YOU KNOW" (60) ===
    "Do you know say before Nigeria get internet, people dey read newspaper for bus stop? Now we scroll TikTok. Time don change.",
    "Random fact: Pigeons can recognize human faces. So that bird wey dey look at you for Ojuelegba, e know you.",
    "Do you know say your stomach get its own nervous system? Dem call am second brain. So when you say *my belly don tell me*, e true.",
    "Bananas are technically berries. But strawberries no be berries. Nature just dey joke with us.",
    "Do you know say octopus get three hearts. Two stop when e swim. Imagine three heartbreaks at once.",
    "Your brain cannot feel pain. That is why surgeon fit operate on you while you dey awake. Scary but true.",
    "Do you know say honey never spoils. Archaeologists find 3000-year-old honey for Egypt wey still sweet. Marriage no reach that level.",
    "Sloths can hold their breath longer than dolphins. 40 minutes for sloth vs 10 for dolphin. Slow and steady.",
    "Do you know say Wizkid and Burna Boy don collaborate before. People still dey fight for who better. E no finish.",
    "Your bones are stronger than steel. But your heart? One wrong text fit break am. Double standard.",
    "Do you know say Nigeria get over 500 languages. But we still dey struggle to understand women.",
    "Cows have best friends and get stressed when separated. Meat still sweet though. Life is complicated.",
    "Do you know say the average person eats about 1-2 spiders while sleeping in their lifetime. No be lie.",
    "Your nose can remember 50,000 different scents. But you go still forget where you keep your keys.",
    "Do you know say the Eiffel Tower grows taller in summer because heat makes metal expand. Like Lagos rent prices.",
    "Sharks are older than trees. Sharks don dey for 400 million years. Trees came 350 million years ago. The sea gets it.",
    "Do you know say the most common name in the world is Mohammed. In Naija, na Maryam or something else?",
    "Your heart beats about 100,000 times a day. Each beat na another chance to annoy someone on Instagram.",
    "Do you know say the first email was sent in 1971. The first spam email came two years later. People never change.",
    "Butterflies taste with their feet. So when one land on you, e dey check if you sweet.",
    "Do you know say Nigeria flag was designed by a student in 1959. Michael Taiwo Akinkunmi. Rest in peace to the legend.",
    "A group of flamingos is called a flamboyance. A group of Nigerians on Twitter is called a chaos.",
    "Do you know say the human body contains enough iron to make a 3-inch nail. Enough anger to make 1000 tweets.",
    "Octopus have blue blood. No, not royalty blue. Actual blue. Because copper instead of iron.",
    "Do you know say the shortest war in history lasted 38 minutes. Some arguments for gender war don last longer than that.",
    "Your eyes can distinguish about 10 million different colors. But you still cannot tell if that dress is blue or gold.",
    "Do you know say the loudest animal on earth is the sperm whale. But the loudest on Instagram is that your cousin.",
    "Crocodiles cannot stick out their tongues. But they can still bite your hand. Prioritize.",
    "Do you know say the first product to have a barcode was Wrigley's gum. Now everything get barcode. Even your life get price tag.",
    "A day on Venus is longer than a year on Venus. One day dey last 243 Earth days. Imagine that wahala.",
    "Do you know say Nigeria gets more rainfall than London. But our drainage still no dey work. Make una ask questions.",
    "Koalas have fingerprints almost identical to humans. So if one rob a bank, forensic go dey confused.",
    "Do you know say the first computer mouse was made of wood. Like the chair your papa dey use for parlor.",
    "A hippo's sweat is red and acts as sunscreen. Some humans need to learn from hippo.",
    "Do you know say the TikTok logo was designed in 2017. Now e don control the world. Scary fast.",
    "Sea cucumbers can expel their organs to confuse predators and grow new ones. Some ex no fit regrow dignity.",
    "Do you know say the inventor of the frisbee was turned into a frisbee after he died. His ashes put inside. Respect.",
    "The human nose can detect over 1 trillion different smells. But you cannot smell danger when your ex texts.",
    "Do you know say the hashtag symbol # is actually called an octothorpe. Now e just be *hashtag*.",
    "A tiger's roar can be heard from 3 kilometers away. Some people's WhatsApp forwards can be heard from 3 planets away.",
    "Do you know say the first Instagram post was a picture of a dog. The dog now don get more followers than you.",
    "The average person will spend six months of their life waiting for red lights to turn green. Add another year waiting for replies.",
    "Do you know say the Nigerian naira has been devalued multiple times. But our expectations still remain high.",
    "Dolphins have names for each other. They whistle their own name. Meanwhile humans forget names immediately.",
    "Do you know say the first YouTube video was titled 'Me at the zoo'. 19 seconds. Now people dey upload 19 hours of nonsense.",
    "A flock of crows is called a murder. A group of your friends is called a *let's eat*.",
    "Do you know say the most followed Instagram account is Instagram itself. Meta really said control the game.",
    "Your skin sheds about 30,000 cells every minute. So everywhere you go, you leave little pieces of yourself. Poetic and creepy.",
    "Do you know say the first emoji was created in 1999. Now we cannot type without them. We have become the problem.",
    "The average person laughs about 15 times a day. On Yabaleft, maybe 15 times per scroll.",
    "Do you know say Nigeria has the highest twin birth rate in the world. Especially Igbo land. Something for the water.",
    "Ostriches can run faster than horses. But they still cannot outrun their bills at the end of the month.",
    "Do you know say the dot over the letter i is called a tittle. Now you know something useless for your next argument.",
    "The human attention span is now shorter than a goldfish's. Goldfish: 9 seconds. Humans: 8 seconds. We are losing.",
    "Do you know say the first iPhone had no app store. Imagine buying phone and e no get Telegram or TikTok. How life take change.",
    "Bees can recognize human faces. So that bee wey follow you for market, e remember you from last time.",
    "Do you know say the longest word in English has 189,819 letters. Try type that one for comment section.",
    "An eagle can spot a rabbit from 3 kilometers away. Some people cannot spot red flags from 3 centimeters.",
    "Do you know say your phone is dirtier than a toilet seat. Yet you go put am near your mouth to talk. Make we think.",
    "The oldest known joke is from 1900 BC and is about a fart. Humans have always been humans."
]